# Generated by Django 3.0 on 2023-09-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0005_auto_20230914_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='category',
        ),
        migrations.AddField(
            model_name='addbook',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
