# Generated by Django 3.0 on 2023-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0008_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='is_avail',
            field=models.BooleanField(default=True),
        ),
    ]
