# Generated by Django 3.0 on 2023-09-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0010_bookrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
