# Generated by Django 3.0 on 2023-09-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0015_auto_20230916_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='bookid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='request_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='userid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
