# Generated by Django 3.0 on 2023-09-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0016_auto_20230916_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='request_date',
        ),
    ]
