# Generated by Django 3.0 on 2023-09-17 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0017_remove_bookrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='bkform',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.AddBook'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='bookavail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='bookname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='bookno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='usform',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
