# Generated by Django 3.0 on 2023-09-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0018_auto_20230917_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='bkform',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='bookavail',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='bookname',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='bookno',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='username',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='usform',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='request_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
