# Generated by Django 3.0 on 2023-09-17 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0019_auto_20230917_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
