# Generated by Django 3.0 on 2023-09-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0020_auto_20230917_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='request_date',
        ),
    ]
