# Generated by Django 3.0 on 2023-09-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0021_remove_bookrequest_request_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
