# Generated by Django 3.0 on 2023-09-18 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0022_delete_bookrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookno', models.CharField(blank=True, max_length=150, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('userid', models.CharField(blank=True, max_length=150, null=True)),
                ('bookname', models.CharField(blank=True, max_length=150, null=True)),
                ('bkd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.AddBook')),
                ('usd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
