# Generated by Django 3.0 on 2023-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0024_auto_20230918_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='userid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
