# Generated by Django 3.0 on 2023-09-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0026_bookrequest_bkd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='bkd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.AddBook'),
        ),
    ]
