# Generated by Django 3.0 on 2023-09-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0030_bookrequest_bkdet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='bkdet',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.AddBook'),
        ),
    ]
