# Generated by Django 3.0 on 2023-09-19 13:35

import LibraryApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0035_auto_20230918_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=LibraryApp.models.expiry)),
                ('is_avail', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='bkdet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.AddBook'),
        ),
    ]
