# Generated by Django 3.0 on 2023-09-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0036_auto_20230919_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='bkdet',
        ),
    ]
