# Generated by Django 3.0 on 2023-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0037_remove_bookrequest_bkdet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sgen',
            field=models.CharField(choices=[('h', 'Select Your Gender'), ('M', 'Male'), ('F', 'Female')], default='h', max_length=5),
        ),
    ]
