# Generated by Django 3.0 on 2023-09-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0039_auto_20230921_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='add_by',
        ),
    ]
