# Generated by Django 3.0 on 2023-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0040_remove_addbook_add_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bstatus',
            field=models.BooleanField(default=True),
        ),
    ]
