# Generated by Django 3.0 on 2023-09-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0041_auto_20230921_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bstatus',
            field=models.BooleanField(default=False),
        ),
    ]
