# Generated by Django 3.0 on 2023-09-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0042_auto_20230921_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
    ]
