# Generated by Django 3.0 on 2023-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0012_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='bookname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
