# Generated by Django 3.0 on 2023-09-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0013_auto_20230916_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
